### ISSUE TITLE
创建fate-serving发现KubeFATE/k8s-deploy/examples/party-9999/cluster-serving.yaml中ingress host没有生效

### ISSUE THREAD

**Issue by caihy05** [FederatedAI/KubeFATE#587] opened 2022-04-14 09:31 UTC
**What deployment mode you are use?  **
Kuberentes
**What KubeFATE and FATE version you are using?  **
```
kubefate version
* kubefate commandLine version=v1.4.3
* kubefate service version=v1.4.3
```

**What happen?**
安装示例中的fate-serving，修改了ingress中的host,并没有生效而且也不是文件默认地址，安装文件使用KubeFATE/k8s-deploy/examples/party-9999/cluster-serving.yaml
`kubefate cluster install -f examples/party-9999/cluster-serving.yaml`
```
kubectl get ing -n fate-serving-9999 
NAME            CLASS    HOSTS                             ADDRESS   PORTS   AGE
serving-admin   <none>   9999.serving-admin.kubefate.net             80      25m
serving-proxy   <none>   9999.serving-proxy.kubefate.net             80      25m
```
**Screenshots**
![image](https://user-images.githubusercontent.com/22835153/163356764-d9ceeff1-c2d0-4c06-9c07-dc269fd33672.png)

![image](https://user-images.githubusercontent.com/22835153/163356693-984cfec1-d968-4cb6-b579-e4fd050565a4.png)

**Comment by JingChen23** [comment] 2022-04-20 05:20
Thanks for reporting the issue.

Please run `helm list -A` to check your helm releases
Then run `helm get values <your_release> -n <your_namespace>`
you should see the result, let's paste them here and let's see what values are used to populate the template. 

Also, please run `docker images` and let's see which images you are using.

**Comment by JingChen23** [comment] 2022-06-28 07:21
I cannot reproduce the issue in fate-serving v2.1.5, close this issue.

**Closed by JingChen23** 2022-06-28 07:21 UTC
