### ISSUE TITLE
断电重启集群换ip后，kubefate无法恢复，重装也无法恢复

### ISSUE THREAD

**Issue by huisoftware** [FederatedAI/KubeFATE#220] opened 2020-08-29 02:46 UTC
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
kubefate service version=v1.0.2
kubefate commandLine version=v1.0.2
fate=1.3.0-a

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

**Desktop (please complete the following information):**
OS: centos7

**To Reproduce**
Clear how to reproduce your problem.
k8s一台master两台worker
电脑断电换机房，忘了冻结镜像，而且ip地址被占用，其中一台work需要修改ip地址，修改后重启docker和kubelet，k8s集群恢复，发现kubefate无法使用，如下图1，其所有pod都正常。将fate集群通过helm卸载，卸载kubefate，重装kubefate，如下图1，依然无法使用。尝试过删除MongoDB的volume重装，依然如此。

**Screenshots**
![image](https://user-images.githubusercontent.com/25874832/91626689-10175000-e9e4-11ea-9403-504d928e7a00.png)

![image](https://user-images.githubusercontent.com/25874832/91626682-f970f900-e9e3-11ea-9ea6-dccaaebe8df4.png)

**Comment by owlet42** [comment] 2020-08-31 05:53
The config.yaml file must exist in the working directory of the kubefate command line.

Check whether your cluster ingress is normal and whether the configuration of the kubefate.net hosts file is correct.

**Comment by LaynePeng** [comment] 2020-11-14 09:36
Close the issue cuz the cause has been explained

**Closed by LaynePeng** 2020-11-14 09:36 UTC
