### ISSUE TITLE
Connection refuse error when running toy_example after deployment

### ISSUE THREAD

**Issue by pandeBJ** [FederatedAI/KubeFATE#28] opened 2019-11-12 01:46 UTC
I followed the docker-deployment construction to deploy Fate1.1. All the services have been started up. but there was an connection refuse error when running toy_example. i have checked the logs and have no idea about it. could you please help to look into it? thanks.

deployment configuration and error logs are shown as below.

![image](https://user-images.githubusercontent.com/46129889/68634667-2d7b3c00-04ee-11ea-871d-deb655d6852f.png)

[fate_flow_debug.log](https://github.com/FederatedAI/KubeFATE/files/3833933/fate_flow_debug.log)
[fate-proxy.log](https://github.com/FederatedAI/KubeFATE/files/3833934/fate-proxy.log)
[eggroll-meta-service.log](https://github.com/FederatedAI/KubeFATE/files/3833935/eggroll-meta-service.log)
[eggroll-egg.log](https://github.com/FederatedAI/KubeFATE/files/3833936/eggroll-egg.log)

**Comment by LordGoodman** [comment] 2019-11-12 02:26
It seems like your storage service was not working as intended, please log in to the `egg` container and check the `/data/projects/fate/eggroll/storage-service-cxx/logs/` dir for more info about the status of the storage service.

**Comment by jiahaoc1993** [comment] 2019-11-18 10:26
@pandeBJ can I close the issue right now?

**Closed** 2019-11-20 10:46 UTC
